# Generated by Django 6.0.3 on 2026-04-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0002_alter_role_options_role_name_alter_role_id_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Фамилия"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="patronymic",
            field=models.CharField(blank=True, max_length=100, verbose_name="Отчество"),
        ),
    ]
