# Generated by Django 6.0.3 on 2026-04-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
