# Generated by Django 6.0.3 on 2026-04-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_teacher_options'),
        ('Shedule', '0002_rename_faculti_faculty_rename_faculti_groups_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('TEACHER', 'Преподаватель'), ('DEAN', 'Декан'), ('DIRECTOR', 'Директор'), ('ACADEMIC', 'Ученый отдел'), ('STAROSTA', 'Староста'), ('STUDENT', 'Студент')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Конкретная кафедра'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Выберите предметы, которые преподаватель ведёт.', null=True, related_name='teachers', to='Shedule.subject', verbose_name='Предметы'),
        ),
    ]
