# Generated by Django 6.0.3 on 2026-03-30 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Shedule", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fio", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="./static/media/no_avatar.jpeg",
                        null=True,
                        upload_to="./teacher_avatars/",
                    ),
                ),
                (
                    "faculti",
                    models.CharField(
                        choices=[
                            (
                                "Факультет топлива и экологии",
                                "Факультет топлива и экологии",
                            ),
                            ("Механический факультет", "Механический факультет"),
                            (
                                "Факультет информационных технологий и экономики",
                                "Факультет информационных технологий и экономики",
                            ),
                            ("Энергетический факультет", "Энергетический факультет"),
                            ("Заочный факультет", "Заочный факультет"),
                            ("Факультет сервиса", "Факультет сервиса"),
                            (
                                "Факультет техносферной безопасности и права",
                                "Факультет техносферной безопасности и права",
                            ),
                        ],
                        max_length=255,
                        verbose_name="Факультет",
                    ),
                ),
                ("subjects", models.TextField(verbose_name="Ведущие предметы")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Администратор", "Администратор"),
                            ("Преподаватель", "Преподаватель"),
                            ("Студент", "Студент"),
                        ],
                        default="Teacher",
                        max_length=50,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Shedule.groups",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Номер зачетки",
                    ),
                ),
                (
                    "familiy",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Фамилия"),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Имя"),
                ),
                (
                    "otchestvo",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Отчество"),
                ),
                (
                    "faculti",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Факультет топлива и экологии",
                                "Факультет топлива и экологии",
                            ),
                            ("Механический факультет", "Механический факультет"),
                            (
                                "Факультет информационных технологий и экономики",
                                "Факультет информационных технологий и экономики",
                            ),
                            ("Энергетический факультет", "Энергетический факультет"),
                            ("Заочный факультет", "Заочный факультет"),
                            ("Факультет сервиса", "Факультет сервиса"),
                            (
                                "Факультет техносферной безопасности и права",
                                "Факультет техносферной безопасности и права",
                            ),
                        ],
                        default="",
                        max_length=255,
                        verbose_name="Факультет",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="./profile_avatars/"),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Администратор", "Администратор"),
                            ("Преподаватель", "Преподаватель"),
                            ("Студент", "Студент"),
                        ],
                        default="Student",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=12,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "dean",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Власова Маргарита Юрьевна", "Власова Маргарита Юрьевна"),
                            (
                                "Котелевская Мария Александровна",
                                "Котелевская Мария Александровна",
                            ),
                            (
                                "Исаева Марина Владимировна",
                                "Исаева Марина Владимировна",
                            ),
                            ("Куликова Елена Сергеевна", "Куликова Елена Сергеевна"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "birthday",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Shedule.groups",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kurator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_kurator_group",
                        to="Profile.teacher",
                        verbose_name="Куратор",
                    ),
                ),
            ],
        ),
    ]
