# Generated by Django 6.0.3 on 2026-04-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0002_alter_profile_dean"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="group",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="user",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
