# Generated by Django 6.0.3 on 2026-04-23 20:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Shedule", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(max_length=2, verbose_name="Оценка или Н")),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата урока"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Shedule.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Успеваемость",
                "verbose_name_plural": "Успеваемость",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="RecordBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.IntegerField(verbose_name="Итоговая оценка")),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("Зачет", "Зачет"),
                            ("Экзамен", "Экзамен"),
                            ("Курсовая", "Курсовая работа"),
                        ],
                        default="Экзамен",
                        max_length=20,
                    ),
                ),
                ("semester", models.IntegerField(default=1)),
                ("date_signed", models.DateField(auto_now_add=True)),
                ("time_signed", models.TimeField(auto_now_add=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Shedule.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_grades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись в зачетке",
                "verbose_name_plural": "Зачетная книжка",
                "unique_together": {("student", "subject", "semester")},
            },
        ),
    ]
