# Generated by Django 6.0.3 on 2026-04-08 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Journal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="performance",
            options={
                "ordering": ["-date"],
                "verbose_name": "Успеваемость",
                "verbose_name_plural": "Успеваемость",
            },
        ),
    ]
