# Generated by Django 6.0.3 on 2026-04-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Journal", "0002_alter_performance_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordbook",
            name="time_signed",
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
