# Generated by Django 5.1.6 on 2025-03-06 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Kurator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, default='', null=True, upload_to='./teacher_avatars/')),
                ('faculti', models.CharField(choices=[('Факультет топлива и экологии', 'Факультет топлива и экологии'), ('Механический факультет', 'Механический факультет'), ('Факультет информационных технологий и экономики', 'Факультет информационных технологий и экономики'), ('Энергетический факультет', 'Энергетический факультет'), ('Заочный факультет', 'Заочный факультет'), ('Факультет сервиса', 'Факультет сервиса'), ('Факультет техносферной безопасности и права', 'Факультет техносферной безопасности и права')], max_length=255)),
                ('subjects', models.TextField()),
                ('group', models.CharField(choices=[('21.02.16 Шахтное строительство', '21.02.16 Шахтное строительство'), ('21.02.17 Подземная разработка месторождений полезных ископаемых', '21.02.17 Подземная разработка месторождений полезных ископаемых'), ('13.02.03 Электрические станции, сети и системы', '13.02.03 Электрические станции, сети и системы'), ('13.02.02 Теплоснабжение и теплотехническое оборудование', '13.02.02 Теплоснабжение и теплотехническое оборудование'), ('13.02.06 Релейная защита и автоматизация электроэнергетических систем', '13.02.06 Релейная защита и автоматизация электроэнергетических систем'), ('13.02.11 Техническая эксплуатация и обслуживание электрического и электромеханического оборудования (по отраслям)', '13.02.11 Техническая эксплуатация и обслуживание электрического и электромеханического оборудования (по отраслям)'), ('15.02.12 Монтаж, техническое обслуживание и ремонт промышленного оборудования (по отраслям)', '15.02.12 Монтаж, техническое обслуживание и ремонт промышленного оборудования (по отраслям)'), ('18.02.09 Переработка нефти и газа', '18.02.09 Переработка нефти и газа'), ('23.02.01 Организация перевозок и управление на транспорте (автомобильном)', '23.02.01 Организация перевозок и управление на транспорте (автомобильном)'), ('23.02.07 Техническое обслуживание и ремонт двигателей, систем и агрегатов автомобилей', '23.02.07 Техническое обслуживание и ремонт двигателей, систем и агрегатов автомобилей'), ('23.02.05 Эксплуатация транспортного электрооборудования и автоматики (автомобильный транспорт)', '23.02.05 Эксплуатация транспортного электрооборудования и автоматики (автомобильный транспорт)'), ('20.02.02 Защита в чрезвычайных ситуациях', '20.02.02 Защита в чрезвычайных ситуациях'), ('09.02.01 Компьютерные системы и комплексы', '09.02.01 Компьютерные системы и комплексы'), ('20.02.01 Рациональное использование природохозяйственных комплексов', '20.02.01 Рациональное использование природохозяйственных комплексов'), ('38.02.01 Экономика и бухгалтерский учет (по отраслям)', '38.02.01 Экономика и бухгалтерский учет (по отраслям)'), ('38.02.03 Операционная деятельность в логистике', '38.02.03 Операционная деятельность в логистике'), ('09.02.07 Информационные системы и программирование', '09.02.07 Информационные системы и программирование'), ('10.02.05 Обеспечение информационной безопасности автоматизированных систем', '10.02.05 Обеспечение информационной безопасности автоматизированных систем'), ('46.02.01 Документационное обеспечение управления и архивоведение.', '46.02.01 Документационное обеспечение управления и архивоведение.'), ('09.02.06 Сетевое и системное администрирование', '09.02.06 Сетевое и системное администрирование'), ('40.02.01 Право и организация социального обеспечения', '40.02.01 Право и организация социального обеспечения'), ('15.01.05 Сварщик (ручной и частично механизированной сварки (наплавки))', '15.01.05 Сварщик (ручной и частично механизированной сварки (наплавки))'), ('43.01.09 Повар, кондитер', '43.01.09 Повар, кондитер')], max_length=113)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('faculti', models.CharField(choices=[('Факультет топлива и экологии', 'Факультет топлива и экологии'), ('Механический факультет', 'Механический факультет'), ('Факультет информационных технологий и экономики', 'Факультет информационных технологий и экономики'), ('Энергетический факультет', 'Энергетический факультет'), ('Заочный факультет', 'Заочный факультет'), ('Факультет сервиса', 'Факультет сервиса'), ('Факультет техносферной безопасности и права', 'Факультет техносферной безопасности и права')], max_length=255)),
                ('avatar', models.ImageField(blank=True, default='', null=True, upload_to='./profile_avatars/')),
                ('role', models.CharField(blank=True, choices=[('Администратор', 'Administrator'), ('Учитель', 'Teacher'), ('Ученик', 'Student')], max_length=50)),
                ('phone', models.IntegerField(blank=True, max_length=11, null=True, verbose_name='constact_whatsapp')),
                ('course', models.IntegerField()),
                ('birthday', models.IntegerField(max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_group', to='main.faculti')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
                ('kurator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_kurator_group', to='main.teacher')),
            ],
        ),
    ]
