# Generated by Django 5.1.6 on 2025-03-13 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.ForeignKey(choices=[('11', '11'), ('12', '12'), ('21', '21'), ('22', '22'), ('31', '31'), ('32', '32'), ('41', '41'), ('42', '42'), ('51', '51'), ('52', '52')], on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Курс'),
        ),
    ]
