# Generated by Django 5.1.6 on 2025-03-13 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='lesson_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lessontime', verbose_name='Время пары'),
        ),
    ]
