# Generated by Django 5.1.6 on 2025-03-06 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.OneToOneField(choices=[('Факультет топлива и экологии', 'Факультет топлива и экологии'), ('Механический факультет', 'Механический факультет'), ('Факультет информационных технологий и экономики', 'Факультет информационных технологий и экономики'), ('Энергетический факультет', 'Энергетический факультет'), ('Заочный факультет', 'Заочный факультет'), ('Факультет сервиса', 'Факультет сервиса'), ('Факультет техносферной безопасности и права', 'Факультет техносферной безопасности и права')], max_length=255, on_delete=django.db.models.deletion.CASCADE, to='main.faculti'),
        ),
    ]
