# Generated by Django 5.1.6 on 2025-03-15 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AddField(
            model_name='groups',
            name='course',
            field=models.ForeignKey(blank=True, choices=[('11', '11'), ('12', '12'), ('21', '21'), ('22', '22'), ('31', '31'), ('32', '32'), ('41', '41'), ('42', '42'), ('51', '51'), ('52', '52')], default='11', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='groups',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups', verbose_name='Группа'),
        ),
    ]
