# Generated by Django 5.1.6 on 2025-03-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_groups_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название группы'),
        ),
    ]
