# Generated by Django 5.1.6 on 2025-03-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_groups_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='subjects',
        ),
        migrations.AddField(
            model_name='schedule',
            name='subjects',
            field=models.CharField(default='Не указано', max_length=255, verbose_name='Предметы'),
        ),
    ]
