# Generated by Django 5.1.6 on 2025-03-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_schedule_subjects_schedule_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='course',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='11', max_length=2, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2, verbose_name='Курс'),
        ),
    ]
