# Generated by Django 5.1.6 on 2025-03-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontime',
            name='lesson_number',
            field=models.CharField(max_length=1, verbose_name='Номер пары'),
        ),
    ]
