# Generated by Django 6.0.3 on 2026-04-23 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        verbose_name="Название курса (напр. 1 курс или 11)",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Порядок сортировки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Faculti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название факультета"
                    ),
                ),
            ],
            options={
                "verbose_name": "Факультет",
                "verbose_name_plural": "Факультеты",
            },
        ),
        migrations.CreateModel(
            name="Kurator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Куратор")),
            ],
            options={
                "verbose_name": "Куратор",
                "verbose_name_plural": "Кураторы",
            },
        ),
        migrations.CreateModel(
            name="LessonTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson_number",
                    models.CharField(max_length=2, verbose_name="Номер пары"),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="Начало пары"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="Конец пары"),
                ),
            ],
            options={
                "verbose_name": "Время пары",
                "verbose_name_plural": "Времена пар",
                "db_table": "lesson_time",
                "ordering": ["lesson_number"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Предмет")),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_list",
                        to="Accounts.teacher",
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
            },
        ),
        migrations.CreateModel(
            name="Groups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название группы"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Shedule.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "faculti",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="Shedule.faculti",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="groups",
                        to="Shedule.subject",
                        verbose_name="Учебный план группы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "Понедельник"),
                            (2, "Вторник"),
                            (3, "Среда"),
                            (4, "Четверг"),
                            (5, "Пятница"),
                            (6, "Суббота"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                ("room", models.CharField(max_length=255, verbose_name="Аудитория")),
                (
                    "is_even_week",
                    models.BooleanField(
                        blank=True,
                        help_text="Если установлено, занятие идет только в четную или нечетную неделю.",
                        null=True,
                        verbose_name="Четная неделя",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Shedule.groups",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "lesson_time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Shedule.lessontime",
                        verbose_name="Время пары",
                    ),
                ),
                (
                    "merged_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Выберите группы, которые также участвуют в этом занятии.",
                        related_name="merged_schedules",
                        to="Shedule.groups",
                        verbose_name="Объединенные группы",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedules",
                        to="Accounts.teacher",
                        verbose_name="Преподаватель",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Shedule.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание",
                "verbose_name_plural": "Расписания",
                "db_table": "schedule",
                "ordering": ["weekday", "lesson_time__lesson_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "weekday", "lesson_time", "is_even_week"),
                        name="unique_schedule_slot",
                    )
                ],
            },
        ),
    ]
