# Generated by Django 6.0.3 on 2026-03-30 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faculti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kurator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson_number",
                    models.CharField(max_length=1, verbose_name="Номер пары"),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="Начало пары"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="Конец пары"),
                ),
                (
                    "start_time_1",
                    models.TimeField(blank=True, null=True, verbose_name="Начало первой части"),
                ),
                (
                    "end_time_1",
                    models.TimeField(blank=True, null=True, verbose_name="Конец первой части"),
                ),
                (
                    "start_time_2",
                    models.TimeField(blank=True, null=True, verbose_name="Начало второй части"),
                ),
                (
                    "end_time_2",
                    models.TimeField(blank=True, null=True, verbose_name="Конец второй части"),
                ),
            ],
            options={
                "verbose_name": "Время пары",
                "verbose_name_plural": "Времена пар",
                "ordering": ["lesson_number"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Предмет")),
                (
                    "teacher_name",
                    models.CharField(max_length=100, verbose_name="ФИО Преподавателя"),
                ),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
            },
        ),
        migrations.CreateModel(
            name="Groups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=255, verbose_name="Название группы"),
                ),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("11", "11"),
                            ("11", "12"),
                            ("21", "21"),
                            ("22", "22"),
                            ("31", "31"),
                            ("32", "32"),
                            ("41", "41"),
                            ("42", "42"),
                            ("51", "51"),
                            ("52", "52"),
                        ],
                        default="11",
                        max_length=2,
                        verbose_name="Курс",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="groups",
                        to="Shedule.subject",
                        verbose_name="Учебный план группы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher_name",
                    models.CharField(max_length=100, verbose_name="Преподаватель"),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "Понедельник"),
                            (2, "Вторник"),
                            (3, "Среда"),
                            (4, "Четверг"),
                            (5, "Пятница"),
                            (6, "Суббота"),
                        ]
                    ),
                ),
                ("room", models.CharField(max_length=255)),
                (
                    "group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="Shedule.groups"),
                ),
                (
                    "lesson_time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Shedule.lessontime",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Shedule.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Занятие",
                "verbose_name_plural": "Расписание",
                "ordering": ["weekday", "lesson_time__lesson_number"],
                "unique_together": {("group", "weekday", "lesson_time")},
            },
        ),
    ]
