# Generated by Django 6.0.3 on 2026-04-07 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0002_alter_role_options_role_name_alter_role_id_user_and_more"),
        ("Shedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="faculti",
            options={"verbose_name": "Факультет", "verbose_name_plural": "Факультеты"},
        ),
        migrations.AlterModelOptions(
            name="kurator",
            options={"verbose_name": "Куратор", "verbose_name_plural": "Кураторы"},
        ),
        migrations.AlterModelOptions(
            name="schedule",
            options={
                "ordering": ["weekday", "lesson_time__lesson_number"],
                "verbose_name": "Расписание",
                "verbose_name_plural": "Расписания",
            },
        ),
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="lessontime",
            name="end_time_1",
        ),
        migrations.RemoveField(
            model_name="lessontime",
            name="end_time_2",
        ),
        migrations.RemoveField(
            model_name="lessontime",
            name="start_time_1",
        ),
        migrations.RemoveField(
            model_name="lessontime",
            name="start_time_2",
        ),
        migrations.AddField(
            model_name="course",
            name="name",
            field=models.CharField(
                default=None,
                max_length=50,
                verbose_name="Название курса (напр. 1 курс или 11)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Порядок сортировки"
            ),
        ),
        migrations.AddField(
            model_name="faculti",
            name="name",
            field=models.CharField(
                default=None,
                max_length=255,
                unique=True,
                verbose_name="Название факультета",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="groups",
            name="faculti",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="Shedule.faculti",
            ),
        ),
        migrations.AddField(
            model_name="kurator",
            name="name",
            field=models.CharField(
                default=None, max_length=255, verbose_name="Куратор"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule",
            name="is_even_week",
            field=models.BooleanField(
                blank=True,
                help_text="Если установлено, занятие идет только в четную или нечетную неделю.",
                null=True,
                verbose_name="Четная неделя",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="merged_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите группы, которые также участвуют в этом занятии.",
                related_name="merged_schedules",
                to="Shedule.groups",
                verbose_name="Объединенные группы",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="Accounts.teacher",
                verbose_name="Преподаватель",
            ),
        ),
        migrations.AlterField(
            model_name="groups",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Shedule.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="groups",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название группы"),
        ),
        migrations.AlterField(
            model_name="lessontime",
            name="lesson_number",
            field=models.CharField(max_length=2, verbose_name="Номер пары"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Shedule.groups",
                verbose_name="Группа",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="lesson_time",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Shedule.lessontime",
                verbose_name="Время пары",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="room",
            field=models.CharField(max_length=255, verbose_name="Аудитория"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (1, "Понедельник"),
                    (2, "Вторник"),
                    (3, "Среда"),
                    (4, "Четверг"),
                    (5, "Пятница"),
                    (6, "Суббота"),
                ],
                verbose_name="День недели",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="teacher_name",
            field=models.CharField(max_length=100, verbose_name="ФИО преподавателя"),
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(
                fields=("group", "weekday", "lesson_time", "is_even_week"),
                name="unique_schedule_slot",
            ),
        ),
        migrations.AlterModelTable(
            name="lessontime",
            table="lesson_time",
        ),
        migrations.AlterModelTable(
            name="schedule",
            table="schedule",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="teacher_name",
        ),
    ]
