# Generated by Django 6.0.3 on 2026-04-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_teacher_options'),
        ('Shedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faculti',
            new_name='Faculty',
        ),
        migrations.RenameField(
            model_name='groups',
            old_name='faculti',
            new_name='faculty',
        ),
        migrations.AlterModelTable(
            name='faculty',
            table='Shedule_faculty',
        ),
    ]
