# Generated by Django 6.0.3 on 2026-04-08 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0002_alter_role_options_role_name_alter_role_id_user_and_more"),
        ("Shedule", "0002_alter_course_options_alter_faculti_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={},
        ),
        migrations.RemoveField(
            model_name="subject",
            name="teacher_name",
        ),
        migrations.AddField(
            model_name="subject",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_list",
                to="Accounts.teacher",
                verbose_name="Преподаватель",
            ),
        ),
    ]
